moved deadline commands to be made in a assignment channel
CSC510-Group-25/ClassMateBot pull request #105
Opened 2021-11-25 03:07 UTC by jhnguye4

### Summary

### New Files

### Deleted Files

### Changed Files

### Checklist

- [ ] Did you test your changes locally?  
- [ ] Did your changes pass all existing tests?  
- [ ] Do test cases exist for your changes? If not, please make an issue.

Note: ensure that all new code has test coverage! 

----

#### Closing Issues

Use `closes #XXXX` if your PR resolves an issue.
To close multiple issues, use: `resolves #1, resolves #2, resolves...`

#### Bugs, Notes

 
 

#### Contributors

Use `@author`

2021-11-25 04:27 UTC, snapcat requested changes
Please create a new branch on this repo and copy and paste your changes there. The reason the tests are failing is likely because of the differences between the workflow .env

2021-11-25 04:30 UTC, snapcat requested changes
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 04:30 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
'Please send questions to the #assignments channel.'

Should be:

'Please use this command inside the #assignments channel.'

2021-11-25 05:06 UTC, snapcat commented
Converted to draft!

2021-11-26 01:42 UTC, snapcat requested changes
Also check with @etracey7 since she's also working on deadline.py!

2021-11-26 01:42 UTC, snapcat commented on cogs/deadline.py
> +            return
duethisweek should be useable from anywhere.

```suggestion
```

2021-11-26 01:42 UTC, snapcat commented on cogs/deadline.py
> +            return
timenow should be used anywhere.

```suggestion
```

2021-11-26 01:42 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
Should be:
```suggestion
            await ctx.author.send('Please use this command inside the #assignments channel.')
```

2021-11-26 01:42 UTC, snapcat commented on cogs/deadline.py
> +            await ctx.author.send('Please send questions to the #assignments channel.')
Should be:
```suggestion
            await ctx.author.send('Please use this command inside the #assignments channel.')
```

2021-11-26 01:42 UTC, snapcat commented on cogs/deadline.py
> +            return
duetoday should be usable from anywhere.

```suggestion

```

2021-11-26 01:42 UTC, snapcat commented on cogs/deadline.py
> +            return
coursedue should be usable from anywhere.

```suggestion

```

2021-11-26 01:42 UTC, snapcat commented on cogs/deadline.py
> +            return
listreminders should be usable from anywhere

```suggestion

```

2021-12-05 02:57 UTC, closed without merging

2021-12-05 02:58 UTC, peeyush10234 commented
The task is already being addressed in another PR.