Adding poll Command
CSC510-Group-25/ClassMateBot pull request #107
Opened 2021-11-25 07:58 UTC by peeyush10234

### Summary

Adding Polling Command for the bot

### New Files

cogs/polling.py

### Deleted Files

None

### Changed Files

None

### Checklist

- [[Yes] Did you test your changes locally?  
- [Yes ] Did your changes pass all existing tests?  
- [ ] Do test cases exist for your changes? If not, please make an issue.

Note: ensure that all new code has test coverage! 

----

#### Closing Issues

Closes 
https://github.com/CSC510-Group-25/ClassMateBot/issues/27

#### Contributors

2021-11-25 23:56 UTC, snapcat requested changes
poll should be split into two commands: $poll and $quizpoll

Some bugs also need to be addressed. See: #111 and #109

2021-11-25 23:56 UTC, snapcat commented on cogs/polling.py
> +                        return "Please make sure you are using the format 'poll: {title} [Option1] [Option2] [Option 3]'"
Should be:

```suggestion
                        await ctx.author.send(
                            'To use the poll command, do: $poll {POLL TITLE} [option1] [option2] [option3] ... with up to (5-8) options. \n '
                            'OR, to create an opinion poll with thumbs up/down options: $poll MESSAGE\n'
                            'EX: $poll Is this a good idea?')
                        await ctx.message.delete()
                        return
```

2021-11-25 23:56 UTC, snapcat commented on cogs/polling.py
> +import asyncio
'asyncio' imported but unused (F401)

To shut the bot up:

```suggestion
#import asyncio
```

2021-11-25 23:56 UTC, snapcat commented on cogs/polling.py
> +import random
'random' imported but unused (F401)

To shut the bot up:

```suggestion
#import random
```

2021-11-25 23:56 UTC, snapcat commented on cogs/polling.py
> +        self.emojiLetters = [
Do we need the full alphabet? I think we should limit it to A-F. We need to consider message length as well.

2021-11-25 23:59 UTC, snapcat commented on cogs/polling.py
> +
Missing doc comment!

```suggestion
    # -----------------------------------------------------------------------------------------------------------------
    #    Function: poll(self, ctx)
    #    Description: TODO
    #    Inputs:
    #       - ctx: context of the command
    #       -
    #    Outputs:
    #       - TODO
    # -----------------------------------------------------------------------------------------------------------------
```

2021-11-26 00:05 UTC, snapcat commented on cogs/polling.py
> +                return options
Pylint and codacy: cogs/polling.py:58:12: R1705: Unnecessary "else" after "return" (no-else-return)

```suggestion
            return options
```

2021-11-26 06:10 UTC, snapcat commented on cogs/polling.py
> +                        final_options = []  # There is a better way to do this for sure, but it also works that way
What is final_options for? It doesn't seem to do anything.

2021-11-26 23:40 UTC, snapcat submitted a review, later dismissed
Thanks for approving the refactor! 

I think this is now ready to go!

2021-11-27 00:21 UTC, snapcat approved these changes
Reverted an update from main to keep things clean. Previous approval stands!

2021-11-28 20:54 UTC, shraddhamishra7 approved these changes

2021-11-28 21:51 UTC, merged