Group25 deadline enhance
CSC510-Group-25/ClassMateBot pull request #125
Opened 2021-11-29 22:56 UTC by etracey7

### Summary

Adds enhancements to dealines/reminders

New Commands: 
$overdue
$clearoverdue

New Taks:
Sends reminders if something is due within the hour (runs 1/hour)
Send reminders if something is due that day (runs 1/day at 8:00am EST)

Changes to old commands:
Date input is more flexible and includes timezone option ($addhw, $changeduedate)
Date output is formatted and includes timezone and is sent to user privately ($duetoday, $duethisweek, $listreminders)

### New Files

### Deleted Files

### Changed Files

deadline.py
test_bot.py

### Checklist

- [ ] Did you test your changes locally?  
- [ ] Did your changes pass all existing tests?  
- [ ] Do test cases exist for your changes? If not, please make an issue.

Note: ensure that all new code has test coverage! 

----

#### Closing Issues

Use `closes #XXXX` if your PR resolves an issue.
To close multiple issues, use: `resolves #1, resolves #2, resolves...`
closes #122 
closes #103
closes #22
closes #20 
closes #19

#### Bugs, Notes

 
 

#### Contributors

Use `@author`

2021-11-29 23:17 UTC, snapcat requested changes
Suggestions for pylint fix and instructor commands!

2021-11-29 23:17 UTC, snapcat commented on cogs/deadline.py
>      @commands.command(name="addhw",
Should be instructor only

```suggestion
    @commands.has_role('Instructor')
    @commands.command(name="addhw",
```

2021-11-29 23:17 UTC, snapcat commented on cogs/deadline.py
>      @commands.command(name="changeduedate", pass_context=True,
Should also be instructor only

```suggestion
    @commands.has_role('Instructor')
    @commands.command(name="changeduedate", pass_context=True,
```

2021-11-29 23:17 UTC, snapcat commented on cogs/deadline.py
> +    n.send_reminders_hour.start()
Pylint fix!
Just add # pylint: disable=no-member at the end of the lines. It's a common false positive.

```suggestion
    n.send_reminders_day.start() # pylint: disable=no-member
    n.send_reminders_hour.start() # pylint: disable=no-member
```

2021-11-30 01:18 UTC, snapcat approved these changes

2021-11-30 01:38 UTC, snapcat approved these changes
lgtm

2021-11-30 01:47 UTC, peeyush10234 approved these changes

2021-11-30 01:47 UTC, merged